name: bglugwatch-snappy
version: 'v.0.2.3'
summary: OfflineIMAP
description: |
  BGLUGwatch is a Python 3.x script that shows you the latest information on BGLUG.
  This is the Snappy Edition -- that is, you  won't receive updates as often as running from the direct source code.
  So keep that in mind.
confinement: strict
base: core18

parts:
  bglugwatch-snappy:
    plugin: python
    python-version: python3
    source: https://github.com/thetechrobo/bglugwatch-snappy.git
    stage-packages:
      - python-six

apps:
  bglugwatch-snappy:
    command: /usr/bin/bglugwatch
